### ISSUE TITLE
Build fails with GHC 9.0.1

### ISSUE THREAD

**Issue by asr** [haskell-hvr/deepseq-generics#10]
I could compile with GHC 9.0.1 using
```
cabal install --allow-newer=base --allow-newer=ghc-prim
```

I cannot install the [github](https://github.com/phadej/github) library with GHC 8.10.1 because this issue.

Please bump dependencies on Hackage.

Blocking https://github.com/agda/agda/issues/5406.

**Comment by andreasabel** [comment]
Resolved on hackage: https://github.com/haskell-infra/hackage-trustees/issues/311

**Comment by andreasabel** [comment]
Link to revision: https://hackage.haskell.org/package/deepseq-generics-0.2.0.0/revisions/

**Comment by andreasabel** [comment]
Fixed by #12.
