### ISSUE TITLE
Error compiling with GHC 8.10.1

### ISSUE THREAD

**Issue by asr** [haskell-hvr/deepseq-generics#8]
I could compile with GHC 8.10.1 using
```
cabal install --allow-newer=base --allow-newer=ghc-prim
```

Please bump dependencies on Hackage.

Blocking https://github.com/agda/agda/issues/4582.

**Comment by asr** [comment]
Any news? I cannot install the [github](https://github.com/phadej/github) library with GHC 8.10.1 because this issue.

**Comment by hvr** [comment]
@asr I missed your original issue but it's resolved now!

https://hackage.haskell.org/package/deepseq-generics-0.2.0.0/revisions/
